### ISSUE TITLE
Not working for absolute path patterns anymore

### ISSUE THREAD

**Issue by oblitum** [cortesi/modd#49] opened 2018-01-14 22:01 UTC
I use this package [from Archlinux User Repository](https://aur.archlinux.org/packages/modd) and it just got updated to 0.5 and broke some watching tasks I have that use absolute file patterns, for example:

```
/tmp/mutt/mutt-* {
	prep +onchange: echo @mods
}
```
[This used to work](https://github.com/cortesi/modd/issues/38#issuecomment-326774625) but doesn't anymore.

I've tried a more basic sample:

```
/home/francisco/foo/* {
	prep +onchange: echo @mods
}
```
It also doesn't work, but this does:

```
foo/* {
	prep +onchange: echo @mods
}
```

by executing `modd` from `/home/francisco`. So only relative patterns are working now.

Test setup was with directories and files already existing, `modd` running, and I just `echo foo >> foo/bar-bar.txt` several times.

**Comment by oblitum** [comment] 2018-07-26 01:17
It's still the same behavior on master. `/tmp/` is out of question since I've reproduced in a reduced case with a custom `foo` directory.

**Comment by cortesi** [comment] 2019-08-09 04:07
Hi there. I can't reproduce this on the current master. I've just checked in a test configuration to exercise this at `./test/abspath.conf`. Please test this with the test file, and let me know if you're still seeing this on master.

**Closed by cortesi** 2019-08-09 04:07 UTC

**Comment by oblitum** [comment] 2019-08-09 06:27
Same behavior

```
modd/cmd/modd on  master [?] via 🐹 v1.12.7
[N] ➜ mkdir /tmp/abspath

modd/cmd/modd on  master [?] via 🐹 v1.12.7
[N] ➜ touch /tmp/abspath/abspath-foo

modd/cmd/modd on  master [?] via 🐹 v1.12.7
[I] ➜ n modd.conf

modd/cmd/modd on  master [?] via 🐹 v1.12.7 took 12s
[I] ➜ cat modd.conf
/tmp/abspath/abspath-* {
        prep +onchange: echo @mods
}

modd/cmd/modd on  master [?] via 🐹 v1.12.7
[I] ➜ ./modd
03:22:40: skipping prep: echo "/tmp/abspath/abspath-foo"
```

`echo foo > /tmp/abspath-foo` and `echo foo >> /tmp/abspath-foo` does nothing.

I didn't see any code change attempting a fix for this. Since you can't reproduce and there isn't any attempt at fixing it, there's no purpose in trying it out expecting it solved by magic. So feel free to close it, I'm OK with relative path behavior.

**Comment by oblitum** [comment] 2019-08-09 06:34
Actually. Your test is passing, I `echo`ed wrongly (should have been `echo foo > /tmp/abspath/abspath-foo`).

But it's not working for the foo test case I presented first. Dunno why, it's working for `/tmp` path as in the layout of your testcase, but it is _not_ working for the original test case.
